import type { Opportunity } from "./opportunity";

const collectedAt = "2026-08-21T10:30:00.000Z";

export const opportunities: Opportunity[] = [
  {
    id: "wmd-scrape-verse",
    title: "Into the Scrape-Verse",
    provider: "WeMakeDevs × Bright Data",
    summary: "Build a self-healing web scraper and turn reliable public web data into a useful product.",
    opportunity_type: "hackathon",
    deadline: "2026-08-23T19:00:00.000Z",
    location: "Online",
    remote: true,
    amount_text: "$15,000 in prizes",
    eligibility: ["Developers worldwide", "Solo or teams up to four"],
    tags: ["Web scraping", "AI", "Bright Data"],
    source_url: "https://www.wemakedevs.org/hackathons/scrape-verse",
    collected_at: collectedAt,
  },
  {
    id: "tiktok-techjam-2026",
    title: "TikTok TechJam 2026",
    provider: "TikTok",
    summary: "A 72-hour student challenge to build practical products across AI, security and commerce.",
    opportunity_type: "hackathon",
    deadline: "2026-09-01T04:00:00.000Z",
    location: "Global",
    remote: true,
    amount_text: "$34,500 in cash prizes",
    eligibility: ["College students", "Eligible regions only"],
    tags: ["AI", "Cybersecurity", "Commerce"],
    source_url: "https://tiktoktechjam2026.devpost.com/",
    collected_at: collectedAt,
  },
  {
    id: "hack-for-humanity-summer-2026",
    title: "Hack for Humanity · Summer 2026",
    provider: "Hack for Humanity",
    summary: "Build software for mental health, physical health or concussion recovery in a global event.",
    opportunity_type: "hackathon",
    deadline: "2026-09-05T03:45:00.000Z",
    location: "Global",
    remote: true,
    amount_text: "13+ non-cash prizes",
    eligibility: ["Ages 13+", "Solo or teams up to four"],
    tags: ["Health", "AI", "Social impact"],
    source_url: "https://hack-for-humanity-summer-26.devpost.com/",
    collected_at: collectedAt,
  },
  {
    id: "agents-for-humans-2026",
    title: "Agents for Humans Hackathon",
    provider: "Amazon Web Services",
    summary: "Build an autonomous Strands agent that handles repetitive work and surfaces real decisions.",
    opportunity_type: "hackathon",
    deadline: "2026-09-15T00:00:00.000Z",
    location: "Online",
    remote: true,
    amount_text: "$40,000 in cash prizes",
    eligibility: ["Age of majority", "Regional exclusions apply"],
    tags: ["AI agents", "Automation", "AWS"],
    source_url: "https://agentsforhumans.devpost.com/",
    collected_at: collectedAt,
  },
];
